### ISSUE TITLE
[🐛Bug]: air601的云编译出现编译失败

### ISSUE THREAD

**Issue by Wuqiyang312** [openLuat/LuatOS#100]
### 描述一下这个bug / Describe the bug

 在我想给air601添加tls支持时发现无法编译成功
   "component": {
      "wdt": true,
      "httpsrv": true,
      "gpio": true,
      "tls": true,
      "MBEDTLS_DEBUG_C": true,
      "MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED": true
   },

### 复现步骤 / To Reproduce

创建新构建
选择tls httpsrv wdt gpio
点击保存
开始编译

### 如果正常，应该是什么样 / Expected behavior

编译成功

### 截图 / Screenshots

![image](https://github.com/openLuat/LuatOS/assets/86960631/7c8a08a8-8a05-458b-8453-dc1e415b9db0)

### 日志 / Logs

{
   "id": "7b9agfi7q0hqbq2ip0hg2sk13r",
   "version": 1,
   "chip": "air601",
   "component": {
      "wdt": true,
      "httpsrv": true,
      "gpio": true,
      "tls": true,
      "MBEDTLS_DEBUG_C": true,
      "MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED": true
   },
   "dataFile": null,
   "user": {
      "id": "3hkpn4713ghr3pa79esei6uaqd",
      "email": "wuqiyang312@163.com",
      "phone": ""
   }
}

### PACK包版本 / Version

v1021.air601

### 验证

- [X] 检查过该问题，之前没有人提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] 提供了最小可复现工程或详细的复现步骤，确保开发者可以复现 / The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] 已经提供了完整的报错信息、日志、截图，没有经过删减。

**Comment by wendal** [comment]
构建服务器所在的区域网络故障, 已修复
