### ISSUE TITLE
[🚀新需求]: 求补充air001 I2C的方法，文档只有101、102、103，唯独没有001的

### ISSUE THREAD

**Issue by KalonPeng** [openLuat/LuatOS#104]
### 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.

如题

### 描述您想要的解决方案 / Describe the solution you'd like

如题

### 描述您想要的详细使用步骤描述 / Describe the solution you'd like to use in what way

如题

### 确认信息

- [X] 检查过该需求，之前没有人提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] 这个需求是真实存在的，并且对于本项目来说是必要的
- [X] 我已经提供了该需求的清晰、详细、完整的方案，请按该方案进行实施
- [X] 我认为我提供的信息已经足够，不需要其他人继续完善该需求的其他细节
- [X] 我同意跟进该需求的实施进程，并在适时提供合理的解释与纠正

**Comment by chenxuuu** [comment]
https://gitee.com/openLuat/luatos-soc-air001/tree/master/ModuleDemo/I2C
