### ISSUE TITLE
好东西。不知道这个操作系统能不能用在合宙的4g模块，c_sdk开发上

### ISSUE THREAD

**Issue by chenxiahuaxu** [openLuat/LuatOS#21]
好东西。不知道这个操作系统能不能用在合宙的4g模块，c_sdk开发上，
我在官网上看到合宙是有c_sdk环境开发的，对这个有点兴趣，不过这个开发包好像很久没有维护了

**Comment by chenxiahuaxu** [comment]
好东西。不知道这个操作系统能不能用在合宙的4g模块，c_sdk开发上，我在官网上看到合宙是有c_sdk环境开发的，对这个有点兴趣，不过这个开发包好像很久没有维护了

**Comment by wendal** [comment]
还不能用于4G模块

**Comment by chenxiahuaxu** [comment]
> 还不能用于4G模块

我倒是希望合宙能够参考乐鑫的开源模式，发展c_sdk分支。毕竟做嵌入式c语言目前来讲还是主流。

**Comment by wendal** [comment]
这个我就不清楚了
