### ISSUE TITLE
LuatOS - crypto库

### ISSUE THREAD

**Issue by wendal** [openLuat/LuatOS#28]
- [x] 设计文档
- [x] 平台抽象层实现
- [x] rtt实现

**Comment by chain01** [comment]
MD5，hmac之类的有实现吗？阿里云连接需要用到，测试发现用lua层去计算太慢了（计算一次hmacmd5大概要3秒）消耗内存也很大。看W600介绍中有硬件加解密存在，现在crypto是否已经实现了呢？

**Comment by zozoh** [comment]
看起来还没有
