### ISSUE TITLE
希望增加fs 的函数库中增加配置，可以使用外部spi flash

### ISSUE THREAD

**Issue by xiaofeihe** [openLuat/LuatOS#60]
因为 air302 内部 flash 空间太小， 外挂spi flash 后，使用fs 库不能操作外部flash.
建议增加fs 的函数库中增加配置，可以使用外部spi flash .
增加 lua 的fs 函数，增加对：luat_fs_info 的配合功能。

**Comment by wendal** [comment]
已添加vfs, 下一步就是这个了

**Comment by wendal** [comment]
搞定了

**Comment by wendal** [comment]
在V0006中提供
