### ISSUE TITLE
audio能否直接播放PCM数据

### ISSUE THREAD

**Issue by xyaoo** [openLuat/LuatOS#95]
硬件：Air780E+PA板带小音箱
需求：通过mqtt发送实时语音数据(PCM)设备能同步播放

我测试过播放TTS和本地文件都是可行的，但是我们需要播放的文件太大，本地存不了，所以想实时播放。我尝试使用audio.start(0, audio.PCM, 1, 16000, 16) 和audio.write(0, zbuff)去播放PCM数据没有成功。write函数一直返回false，start启动后喇叭一直播放很尖锐的声音(应该和write没关系，因为我不write也一样)

请问这个功能用LuatOS能实现吗，还是说得CSDK，如果能有相关demo吗？我翻了资料LuatOS/CSDK都只有下来后播放本地文件的demo

**Comment by wendal** [comment]
初始化了吗?

**Comment by xyaoo** [comment]
write前调用了audio.start(0, audio.PCM, 1, 16000, 16)

**Comment by wendal** [comment]
demo/tts 有演示
